media: static/

content:

  - name: content
    label: Content
    type: collection
    path: content/
    view:
      fields: [ title, draft, date ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string }
      - { name: date, label: Date, type: date }
      - { name: draft, label: Draft, type: boolean }
      - { name: body, label: Body, type: rich-text }

  - name: about
    label: About page
    type: file
    path: content/about.md
    fields:
      - { name: body, label: Body, type: rich-text }

  - name: config
    label: Config
    type: file
    path: config.toml
    format: code
