media: static/media

content:

  - name: Index
    label: index
    type: file
    path: content/_index.md
    fields:
      - { name: body, label: Body, type: rich-text }

  - name: contact
    label: Contact
    type: file
    path: content/contact.md
    fields:
      - { name: body, label: Body, type: rich-text }

  - name: posts
    label: Posts
    type: collection
    path: content/posts
    # view:
    #   fields: [ title, draft, date ]
    fields:
      - { name: title, label: Title, type: string, required: true }
      - { name: description, label: Description, type: string }
      - { name: date, label: Date, type: date }
      - { name: draft, label: Draft, type: boolean }
      - { name: body, label: Body, type: rich-text }

  - name: zola-config
    label: Zola config
    type: file
    path: config.toml
    format: toml
