base_url = "https://bolmso.samake.se/"

minify_html = true
build_search_index = true

default_language = "sv"
title = "Bolmenbygdens friskola"

[languages.en]
title = "Bolmenbygdens friskola"

[languages.de]
title = "Bolmenbygdens friskola"

[languages.nl]
title = "Bolmenbygdens friskola"

[markdown]
external_links_target_blank = true
lazy_async_image = true
