title = "Bolmenbygdens friskola"
description = ""
default_language = "sv"
base_url = "https://test-bolmso.samake.se"
minify_html = true
build_search_index = true

[markdown]
external_links_target_blank = true
